apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # Connecting to port 3000 of the clusterIP service gives you access to the <targetPort> of the container
      targetPort: 3000 # You can get access to port 3000 of the container by accessing the <port> of the clusterIP service