apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432 # Connecting to port 5432 of the clusterIP service gives you access to the <targetPort> of the container
      targetPort: 5432 # You can get access to port 5432 of the container by accessing the <port> of the clusterIP service