apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000 # Connecting to port 5000 of the clusterIP service gives you access to the <targetPort> of the container
      targetPort: 5000 # You can get access to port 5000 of the container by accessing the <port> of the clusterIP service